reviewers:
  groups:
    repository-owner:
      - chryzcodez
      
core-contributors:
     # - good-boy  username
     # - good-girl  username
      
      
options:
  ignore_draft: true
  ignored_keywords:
    - DO NOT REVIEW
  enable_group_assignment: false
