on:
  fork:
  push:
    branches: [ master ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:

  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: chryz-hub/chryz-hub.github.io/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '<h1>It''s great having you contribute to this project/ repository</h1> <p>Welcome to the community :nerd_face: Is there anything you are yet to understand, please do well to ask</p>'
          pr-message: '<h1>It''s great having you contribute to this project/ repository</h1> <p>Welcome to the community :nerd_face: Is there anything you are yet to understand, please do well to ask</p>'
          footer: 'Join our Discord and GitHub Organisation'
