on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: Chryz-Hub
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<p><b>Invitation sent for the GitHub Organisation. Welcome to the community 🎉</p></b>' 
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}

