on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: chryz-hub
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<b>Invitation sent for the GitHub Organisation. Welcome to the community 🎉</b><b>Check out for the invitation in your E-mail join the community fully and also do not forget to make this <a href="https://github.com/chryz-hub/opensource-4-everyone/blob/master/My-PR-Contribution-Practice.md">pull request</a> to make out connections and get a green square🟩 today</b><b>You want to customize your profile we got you covered, check out this tutorial-blog<a href="https://chryzcodez.hashnode.dev/how-to-make-your-github-profile-readme>HOW TO MAKE YOUR GITHUB PROFILE README:)</a></b><p> Do not forget, open-soucrce is beyond coding but the comming together of people, ideas, communicating, adding values and solving problems.<b>We hope this set you for the open-source journey ahead!</b>'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
