on:
  issues:
    types: [labeled]

jobs:
  automate_invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite on label
        uses: vj-abigo/invite-on-label@v1.2
        with:
          organization: chryz-hub
          label: invite me to the organization
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          comment: '<p><b>Invitation sent for the GitHub Organisation. Welcome to the community 🎉</p></b> Check out for the invitation sent to your GitHUb registered E-mail to join the community and after accepting that, been a member do not forget to make your <a href="https://github.com/chryz-hub/opensource-4-everyone/blob/master/membership-visibility.md">membership visbility public</a> and make this <a href="https://github.com/chryz-hub/opensource-4-everyone/blob/master/My-PR-Contribution-Practice.md">pull request</a> to make out connections and get a green square 🟩.</p> <b>Do you want to customize your github profile we got you covered</b> Check out this tutorial-blog <a href="https://chryzcodez.hashnode.dev/how-to-make-your-github-profile-readme">HOW TO MAKE YOUR GITHUB PROFILE README:)</a><p> Do not forget, open-soucrce is beyond coding but the comming together of people, ideas, communicating, adding values and solving problems.</p><b>We hope this set you for the open-source journey ahead!</b><p> Join us via <br><a href="https://discord.gg/c6RhGwcP5b"><img src="https://img.shields.io/badge/Discord-7289DA?style=for-the-badge&logo=discord&logoColor=white"></br>'
        env:
          INVITE_TOKEN: ${{ secrets.INVITE_TOKEN }}
