name: Review Assign

on:
  issues : 
    types: [opened]
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          reviewers: chryzcodez, Ukpebor
          max-num-of-reviewers: 1
